// This file is generated by scripts/generate-registry.mjs. Do not edit manually.
import * as module0 from "../../content/item-effects/core";
import * as module1 from "../../content/items/consumables";
import * as module2 from "../../content/items/equipment";
import * as module3 from "../../content/monsters/core";
import * as module4 from "../../content/rooms/core";
import { RegistryModule } from "./types";

const modules: RegistryModule[] = [module0, module1, module2, module3, module4];

export const roomDefinitions = modules.flatMap((module) => module.rooms ?? []);
export const monsterDefinitions = modules.flatMap((module) => module.monsters ?? []);
export const bossDefinitions = modules.flatMap((module) => module.bosses ?? []);
export const equipDefinitions = modules.flatMap((module) => module.equipment ?? []);
export const consumableDefinitions = modules.flatMap((module) => module.consumables ?? []);
export const itemEffectDefinitions = modules.flatMap((module) => module.itemEffects ?? []);

export type RegisteredRoomType = (typeof roomDefinitions)[number]["type"];
